// 自动生成，勿手改。来源：config/void-capabilities.json + .env.example
// 生成：scripts/generate-capabilities-schema.py
import type { ConfigField } from "./config-schema.js";

export const CAPABILITY_FIELDS: ConfigField[] = [
  { key: "autoOpenBrowser", classification: "development_only", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "agentBridgeEnabled", classification: "legacy_or_omit", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade", default: false },
  { key: "agentConfigFile", classification: "void_native", owner: "void-legion", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "agentProtocol", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "agentProvider", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "openai" },
  { key: "agentTimeoutMs", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "agentToolControlConfirmPassword", classification: "adapter_credential", owner: "void-tools", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "agentToolControlMode", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "confirm" },
  { key: "allowedOrigins", classification: "void_native", owner: "void-security", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "assistantExternalDeliveryPreference", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "feishu,qq,community,discord" },
  { key: "assistantModeEnabled", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade", default: false },
  { key: "attachmentMaxFileBytes", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "attachmentMaxTotalBytes", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "attachmentTextCharLimit", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "attachmentTextTotalCharLimit", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "audioTranscriptAppendCharLimit", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "authMode", classification: "void_native", owner: "void-security", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "none" },
  { key: "authPassword", classification: "adapter_credential", owner: "void-security", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "authToken", classification: "adapter_credential", owner: "void-security", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "autoRecallEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "autoRecallLimit", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "autoRecallMinScore", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "autoTaskTimeEnabled", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "autoTaskTokenEnabled", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "browserAllowedDomains", classification: "void_native", owner: "void-browser", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "browserDeniedDomains", classification: "void_native", owner: "void-browser", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "browserOutboundProfile", classification: "void_native", owner: "void-browser", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "public-web" },
  { key: "browserRelayEnabled", classification: "void_native", owner: "void-browser", sensitive: false, reloadMode: "live", failureMode: "degrade", default: false },
  { key: "browserScreenshotAutoUnderstand", classification: "void_native", owner: "void-browser", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "budgetProtectKeepRecentRounds", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "budgetProtectMode", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "cameraNativeHelperArgsJson", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "cameraNativeHelperCommand", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "cameraNativeHelperCwd", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "cameraNativeHelperEnvJson", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "cameraNativeHelperFfmpegArgsJson", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "cameraNativeHelperFfmpegCommand", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "cameraNativeHelperIdleShutdownMs", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "cameraNativeHelperPowershellArgsJson", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "cameraNativeHelperPowershellCommand", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "cameraNativeHelperRequestTimeoutMs", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "cameraNativeHelperStartupTimeoutMs", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "cameraSnapAutoUnderstand", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "carryoverContextEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "channelIngressMaxConcurrent", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "channelIngressMaxConcurrentPerChannel", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "channelIngressMaxPayloadBytes", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "channelIngressMaxPendingPerSession", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "channelIngressMaxQueued", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "channelIngressMaxQueuedPayloadBytes", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "channelIngressMaxWaitMs", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "channelRouterConfigPath", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "channelRouterDefaultAgentId", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "channelRouterEnabled", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "codeIntelGoplsCommand", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "codeIntelGoCommand", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "codeIntelGoEnabled", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "commanderAgentId", classification: "void_native", owner: "void-legion", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "commanderAutoReworkEnabled", classification: "void_native", owner: "void-legion", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "commanderMode", classification: "void_native", owner: "void-legion", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "commandSandboxBackend", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "commandSandboxOciImage", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "commandSandboxOciRuntime", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "commonsObsidianEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade", default: false },
  { key: "commonsObsidianRootDir", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "commonsObsidianVaultPath", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "communityApiEnabled", classification: "legacy_or_omit", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade", default: false },
  { key: "communityApiToken", classification: "adapter_credential", owner: "void-core", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "compactionApiKey", classification: "adapter_credential", owner: "void-core", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "compactionArchivalThreshold", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "compactionBaseUrl", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "compactionBlockingThreshold", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "compactionContextWindowFraction", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "0.8" },
  { key: "compactionEnabled", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "compactionKeepRecent", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: 16 },
  { key: "compactionMaxConsecutiveFailures", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "compactionMaxPtlRetries", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "compactionModel", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "compactionModelRoute", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "compactionThreshold", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: 800000 },
  { key: "compactionTriggerFraction", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "compactionWarningThreshold", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "compressionPersistentReferenceMaxEntries", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "compressionPersistentReferenceStore", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "compressionPersistentReferenceTtlMs", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "compressionReferenceStore", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "contextInjection", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "contextInjectionAllowedCategories", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "contextInjectionIncludeSession", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "contextInjectionLimit", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "contextInjectionTaskLimit", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "conversationAllowedKinds", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "all" },
  { key: "cronEnabled", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade", default: false },
  { key: "dangerousToolsEnabled", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "deepseekRoutePolicyEnabled", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "devRuntimeDistGuard", classification: "development_only", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "discordBotToken", classification: "adapter_credential", owner: "void-channel-discord", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "discordDefaultChannelId", classification: "void_native", owner: "void-channel-discord", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "discordEnabled", classification: "void_native", owner: "void-channel-discord", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "discordRestMaxResponseBytes", classification: "void_native", owner: "void-channel-discord", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "discordRestTimeoutMs", classification: "void_native", owner: "void-channel-discord", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "dreamAutoCronEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade", default: false },
  { key: "dreamAutoHeartbeatEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade", default: false },
  { key: "dreamObsidianEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade", default: false },
  { key: "dreamObsidianRootDir", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "dreamObsidianVaultPath", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "dreamOpenaiMaxTokens", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "dreamOpenaiReasoningEffort", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "dreamOpenaiThinking", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "dreamOpenaiTimeoutMs", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailDefaultProvider", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailImapAccountId", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailImapBootstrapMode", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailImapConnectTimeoutMs", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailImapEnabled", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "emailImapHost", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailImapMailbox", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailImapPass", classification: "adapter_credential", owner: "void-channel-email", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "emailImapPollIntervalMs", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailImapPort", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailImapRecentWindowLimit", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailImapSecure", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailImapSocketTimeoutMs", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailImapUser", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailInboundAgentId", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailOutboundRequireConfirmation", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailSmtpAccountId", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailSmtpEnabled", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "emailSmtpFromAddress", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailSmtpFromName", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailSmtpHost", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailSmtpPass", classification: "adapter_credential", owner: "void-channel-email", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "emailSmtpPort", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailSmtpSecure", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "emailSmtpUser", classification: "void_native", owner: "void-channel-email", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "embeddingBatchSize", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: 2 },
  { key: "embeddingEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade", default: false },
  { key: "embeddingModel", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "text-embedding-3-small" },
  { key: "embeddingOpenaiApiKey", classification: "adapter_credential", owner: "void-memory", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "embeddingOpenaiBaseUrl", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "embeddingPassagePrefix", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "embeddingProvider", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "openai" },
  { key: "embeddingQueryPrefix", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "envDir", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "experienceAutoMethodEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade", default: true },
  { key: "experienceAutoPromotionEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade", default: true },
  { key: "experienceAutoSkillEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade", default: true },
  { key: "experienceSynthesisMaxSimilarSources", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "experienceSynthesisMaxSourceContentChars", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "experienceSynthesisTotalSourceContentCharBudget", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "extensionHostBackend", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "extensionHostOciImage", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "extensionHostOciRuntime", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "externalOutboundRequireConfirmation", classification: "void_native", owner: "void-security", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: true },
  { key: "extraWorkspaceRoots", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "facetAnchor", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "feishuAgentId", classification: "void_native", owner: "void-channel-feishu", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "feishuAppId", classification: "void_native", owner: "void-channel-feishu", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "feishuAppSecret", classification: "adapter_credential", owner: "void-channel-feishu", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "feishuHttpIdleTimeoutMs", classification: "void_native", owner: "void-channel-feishu", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "feishuJsonMaxResponseBytes", classification: "void_native", owner: "void-channel-feishu", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "feishuResourceMaxResponseBytes", classification: "void_native", owner: "void-channel-feishu", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "gatewayPort", classification: "legacy_or_omit", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "28889" },
  { key: "goalExecutionMode", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "goalGovernanceMode", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "heartbeatActiveHours", classification: "defer", owner: "void-automation", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "heartbeatEnabled", classification: "defer", owner: "void-automation", sensitive: false, reloadMode: "live", failureMode: "degrade", default: false },
  { key: "heartbeatInterval", classification: "defer", owner: "void-automation", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "host", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "127.0.0.1" },
  { key: "image", classification: "legacy_or_omit", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "vrboyzero/star-sanctuary:local" },
  { key: "imageAssetAllowedHosts", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageEnabled", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "imageMaxOutputBytes", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageModel", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageOpenaiApiKey", classification: "adapter_credential", owner: "void-media", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "imageOpenaiBaseUrl", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageOutputFormat", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageProvider", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageTimeoutMs", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageUnderstandAutoOnAttachment", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageUnderstandEnabled", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "imageUnderstandMaxInputMb", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageUnderstandMaxWidth", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageUnderstandModel", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageUnderstandOpenaiApiKey", classification: "adapter_credential", owner: "void-media", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "imageUnderstandOpenaiBaseUrl", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageUnderstandPrompt", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageUnderstandProvider", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "imageUnderstandTimeoutMs", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "injectAgents", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "injectMemory", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "injectMethodSkillList", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "injectSoul", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "localEmbeddingModel", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "logConsole", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: true },
  { key: "logDir", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "~/.star_sanctuary/logs" },
  { key: "logFile", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: true },
  { key: "logLevel", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "info" },
  { key: "logMaxSize", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "10MB" },
  { key: "logRetentionDays", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: 7 },
  { key: "maxHighRiskToolCalls", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "maxHistory", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "maxInputTokens", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "maxOutputTokens", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "maxRunWallTimeMs", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "maxSystemPromptChars", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "maxToolCalls", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "maxTotalTokens", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "mcpEnabled", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade", default: false },
  { key: "memoryBackgroundMaxRuns", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryBackgroundMaxTokenUnits", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryBackgroundWindowMs", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryDb", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryDeepRetrieval", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryDurableExtractionCloseDeadlineMs", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryDurableExtractionFailureBackoffMaxMs", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryDurableExtractionFailureBackoffMs", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryDurableExtractionMaxInputBytes", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryDurableExtractionMaxMessages", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryDurableExtractionMaxMessageBytes", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryDurableExtractionMaxRuns", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryDurableExtractionMinMessageDelta", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryDurableExtractionMinPendingMessages", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryDurableExtractionSuccessCooldownMs", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryDurableExtractionWindowMs", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade", default: true },
  { key: "memoryEvolutionApiKey", classification: "adapter_credential", owner: "void-memory", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "memoryEvolutionBaseUrl", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryEvolutionEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "memoryEvolutionMinMessages", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryEvolutionModel", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryIndexerVerboseWatch", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryNodeAssistedRetrieval", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryPrivateSummaryRedactor", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memoryPrivateSummaryTrustedHosts", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memorySessionDigestMaxRuns", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memorySessionDigestWindowMs", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memorySummaryApiKey", classification: "adapter_credential", owner: "void-memory", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "memorySummaryBaseUrl", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "memorySummaryEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "memorySummaryModel", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "methodGenerationConfirmRequired", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "methodPublishConfirmRequired", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "mindProfileRuntimeEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "mindProfileRuntimeMaxChars", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "mindProfileRuntimeMaxLines", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "mindProfileRuntimeMaxLineLength", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "mindProfileRuntimeMinSignalCount", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "modelCacheCreationUsdPer1m", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "modelCacheReadUsdPer1m", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "modelConfigFile", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "modelContextWindow", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "1000000" },
  { key: "modelInputUsdPer1m", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "modelOutputUsdPer1m", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "modelPreferredProviders", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "mv3ChromePath", classification: "development_only", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "officeMaxDownloadBytes", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "openaiApiKey", classification: "adapter_credential", owner: "void-core", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "openaiBaseUrl", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "https://api.openai.com/v1" },
  { key: "openaiMaxRetries", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "openaiModel", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "gpt-4o" },
  { key: "openaiProxyUrl", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "openaiReasoningEffort", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "openaiRetryBackoffMs", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "openaiStream", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "openaiSystemPrompt", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "openaiThinking", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "openaiWireApi", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "port", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: 28889 },
  { key: "preflightAttachmentReference", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "preflightAttachmentThresholdChars", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "preflightCompressionEnabled", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "preflightCompressionMode", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "preflightMinSavingsRatio", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "preflightSidecarMaxEntries", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "preflightSidecarRetentionMs", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "preflightTargetRatio", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "preflightTimeoutMs", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "primaryWarmupCooldownMs", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "primaryWarmupEnabled", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "primaryWarmupTimeoutMs", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "privilegedWorkspaceWriteChannels", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "promptExperimentDisableSections", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "promptExperimentDisableToolContracts", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "promptExperimentSectionPriorityOverrides", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "promptFocusEnabled", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "promptFocusSemanticEnabled", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "promptFocusSemanticMinScore", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "promptSnapshotEmailThreadMaxRuns", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "promptSnapshotHeartbeatMaxRuns", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "promptSnapshotMaxPersistedRuns", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "promptSnapshotMaxRuns", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "promptSnapshotRetentionDays", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "qqAgentId", classification: "void_native", owner: "void-channel-qq", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "qqAppId", classification: "void_native", owner: "void-channel-qq", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "qqAppSecret", classification: "adapter_credential", owner: "void-channel-qq", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "qqEventSampleCaptureDir", classification: "void_native", owner: "void-channel-qq", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "qqEventSampleCaptureEnabled", classification: "void_native", owner: "void-channel-qq", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "qqSandbox", classification: "void_native", owner: "void-channel-qq", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "qqSttFallbackProviders", classification: "void_native", owner: "void-channel-qq", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "relayPort", classification: "void_native", owner: "void-browser", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "remoteDeliveryTargetsJson", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "rerankerLengthNormAnchor", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "rerankerMinScore", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "responsesSanitizeToolSchema", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: true },
  { key: "roomInjectThreshold", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "roomMembersCacheTtl", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "runtimeResourceEventLoopResolutionMs", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "runtimeResourceMaxSamples", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "runtimeResourceObservabilityEnabled", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "runtimeResourceSampleIntervalMs", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "screenCaptureAutoUnderstand", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "sharedReviewClaimTimeoutMs", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "skillGenerationConfirmRequired", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "skillPublishConfirmRequired", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "skipRealBrowserRelayTests", classification: "development_only", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "stablePrefixSplit", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "starweaverActiveNotifyEnabled", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "starweaverActiveNotifyPollIntervalMs", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "stateDir", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "~/.star_sanctuary" },
  { key: "stateDirWindows", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "stateDirWsl", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "sttGroqApiKey", classification: "adapter_credential", owner: "void-media", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "sttGroqBaseUrl", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "sttLanguage", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "sttModel", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "sttOpenaiApiKey", classification: "adapter_credential", owner: "void-media", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "sttOpenaiBaseUrl", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "sttProvider", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "subAgentMaxConcurrent", classification: "void_native", owner: "void-legion", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "subAgentMaxCostUsd", classification: "void_native", owner: "void-legion", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "subAgentMaxDepth", classification: "void_native", owner: "void-legion", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "subAgentMaxQueueSize", classification: "void_native", owner: "void-legion", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "subAgentMaxVerifiers", classification: "void_native", owner: "void-legion", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "subAgentTimeoutMs", classification: "void_native", owner: "void-legion", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "taskDedupGuardEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "taskDedupMode", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "taskDedupPolicy", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "taskDedupWindowMinutes", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "taskMemoryEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "taskStatsWhenMemoryDisabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "taskSummaryApiKey", classification: "adapter_credential", owner: "void-memory", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "taskSummaryBaseUrl", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "taskSummaryEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "taskSummaryMinDurationMs", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "taskSummaryMinTokenTotal", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "taskSummaryMinToolCalls", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "taskSummaryModel", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "teamSharedMemoryEnabled", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "tokenUsageStrictUuid", classification: "legacy_or_omit", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: false },
  { key: "tokenUsageUploadApikey", classification: "legacy_or_omit", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "tokenUsageUploadEnabled", classification: "legacy_or_omit", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: false },
  { key: "tokenUsageUploadTimeoutMs", classification: "legacy_or_omit", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "tokenUsageUploadToken", classification: "adapter_credential", owner: "void-core", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "tokenUsageUploadTrustedPrivateEndpoint", classification: "legacy_or_omit", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "tokenUsageUploadUrl", classification: "legacy_or_omit", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "toolsEnabled", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade", default: true },
  { key: "toolsPolicyFile", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "toolAgentStreamingEnabled", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "toolGroups", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "toolLoopIterationBudget", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "toolLoopWarningFraction", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "toolResultEventOutputCharLimit", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "toolResultTranscriptCharLimit", classification: "void_native", owner: "void-memory", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "ttsEnabled", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "ttsMaxOutputBytes", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "ttsModel", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "ttsOpenaiApiKey", classification: "adapter_credential", owner: "void-media", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "ttsOpenaiBaseUrl", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "ttsProvider", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "edge" },
  { key: "ttsVoice", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "zh-CN-XiaoxiaoNeural" },
  { key: "understandingCacheMaxBytes", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "understandingCacheMaxEntries", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "understandingCacheTtlMs", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "updateCheck", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: true },
  { key: "updateCheckApiUrl", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "updateCheckTimeoutMs", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "videoFileApiKey", classification: "adapter_credential", owner: "void-media", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "videoFileApiUrl", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "videoUnderstandAutoAttachmentMaxTimelineItems", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "videoUnderstandAutoAttachmentSummaryCharLimit", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "videoUnderstandAutoOnAttachment", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "videoUnderstandEnabled", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "live", failureMode: "degrade" },
  { key: "videoUnderstandFps", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "videoUnderstandMaxInputMb", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "videoUnderstandModel", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "videoUnderstandOpenaiApiKey", classification: "adapter_credential", owner: "void-media", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "videoUnderstandOpenaiBaseUrl", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "videoUnderstandPrompt", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "videoUnderstandProvider", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "videoUnderstandTimeoutMs", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "videoUnderstandTransport", classification: "void_native", owner: "void-media", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "webchatCostBudgetUsd", classification: "void_native", owner: "void-entry", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "webchatCostBudgetWarnFraction", classification: "void_native", owner: "void-entry", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "webhookConfigPath", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "webhookIdempotencyWindowMs", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "webhookMaxInFlightPerKey", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "webhookMaxInFlightTrackedKeys", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "webhookPreauthMaxBytes", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "webhookPreauthTimeoutMs", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "webhookRateLimitMaxRequests", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "webhookRateLimitMaxTrackedKeys", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "webhookRateLimitWindowMs", classification: "void_native", owner: "void-channel", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "webAllowPrivilegedSafeScope", classification: "void_native", owner: "void-tools", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "webExperienceDraftGenerateNoticeEnabled", classification: "void_native", owner: "void-entry", sensitive: false, reloadMode: "live", failureMode: "degrade", default: true },
  { key: "webGovernanceDetailMode", classification: "void_native", owner: "void-entry", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "compact" },
  { key: "webRoot", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "workflowAgentTimeoutMs", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "workflowMaxAgentCalls", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "workflowMaxBatchItems", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "workflowMaxBatchOutputBytes", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "workflowMaxBatchQueuedBytes", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "workflowMaxConcurrent", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "workflowMaxDepth", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "workflowMaxQueueSize", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "workflowMaxRetries", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "workflowMaxScriptBytes", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "workflowMaxTokens", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "workflowTimeoutMs", classification: "dsh_mapped", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "workspaceDir", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade", default: "./workspace" },
  { key: "dashscopeApiKey", classification: "adapter_credential", owner: "void-media", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "setupToken", classification: "adapter_credential", owner: "void-core", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "starSanctuaryEnvDir", classification: "void_native", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
  { key: "tailscaleAuthKey", classification: "adapter_credential", owner: "void-core", sensitive: true, reloadMode: "restart", failureMode: "fail_closed" },
  { key: "tailscaleExtraArgs", classification: "legacy_or_omit", owner: "void-core", sensitive: false, reloadMode: "restart", failureMode: "degrade" },
];
