export {
  dataRootOptions,
  FACET_DIRECTORY_NAME,
  isProfileName,
  PROFILE_DIRECTORY_NAME,
  profileLocationFromBaseUrl,
  readProfileDirectory,
  SoulProfileError,
  indexSoulProfiles,
  isFacetDirectoryName,
  parseSoulDocument,
  resolveAgentDirectory,
  resolveHarnessHome,
  resolveVoidDataDir,
  resolveVoidDataRoot,
  tryResolveVoidDataRoot,
  type ParsedSoulDocument,
  type ProfileLocation,
  type SoulAuthority,
  type SoulFrontMatter,
  type VoidDataRootConfig,
  type VoidDataRootOptions,
} from "./profile.js";
export {
  assertAuthorityReferences,
  assertMayDirect,
  assertMayDirectAll,
  authorityProfileOf,
  buildAuthorityProfiles,
  type AuthorityProfile,
  type AuthoritySnapshot,
  type AuthoritySource,
} from "./authority.js";
export { assertRawCommandAllowed, isExecutionAllowed, type ExecutionIsolation, type ExecutionPolicy } from "./execution-policy.js";
export { buildMemberPersona, personaTextOf, type MemberPersona } from "./persona.js";
export { runGuardedCommand, type RawCommandRequest } from "./command-gate.js";
export { guardShell, installShellReadGuard, type GuardedShell } from "./shell-guard.js";
export {
  assertPathInsideRoots,
  assertRealPathInsideRoots,
  assertRealPathInsideRootsSync,
  normalizeHostPath,
  PathGuardError,
  type PathGuardOptions,
} from "./path-guard.js";
export {
  assertToolEntryAllowed,
  classifyToolEntry,
  entryDenialReason,
  EntryPolicyError,
  type EntryPolicyOptions,
  type ToolContractLike,
  type ToolEntryKind,
} from "./entry-policy.js";
export {
  installToolEntryGuard,
  type GuardedToolExecution,
  type GuardedToolRegistry,
  type ToolEntryGuardChannel,
  type ToolEntryGuardResult,
} from "./tool-entry-guard.js";
export {
  bindSession,
  loadSessionBindings,
  saveSessionBindings,
  loadSoulRegistry,
  resolveBinding,
  type SessionBinding,
  type SoulRecord,
} from "./registry.js";
export {
  assertPromptRenderable,
  beginPrompt,
  describeAppliedRecord,
  describeFacetVersions,
  describePending,
  facetVersionWidget,
  FACET_VERSION_WIDGET_ID,
  renderFacetVersionLines,
  parseFacetCard,
  parseFacetState,
  markFirstMeeting,
  PROMPT_VARIABLES,
  PROMPT_VARIABLE_SOURCES,
  recordAppliedPrompt,
  replaceSavedFacet,
  selectFacet,
  setSuspended,
  suspendedReason,
  snapshotPrompt,
  measurePromptText,
  type AgentFacetState,
  type AppliedPrompt,
  type AppliedPromptRecord,
  type FacetCard,
  type FacetPendingReason,
  type FacetVersionView,
  type PromptMeasurement,
  type PromptSnapshot,
  type PromptVariableValues,
} from "./facet.js";
export { AppliedPromptRegistry } from "./applied-prompts.js";
export { facetViewRegistration, loadFacetLibrary, loadFacetRegistrations, loadFirstMeetingView, loadProfileFacetRegistrations, loadSavedFacetView, saveFacetSelection, saveFirstMeetingState, saveProfileFacetSelection, saveProfileSuspension, type FacetWidgetRegistration, type FirstMeetingView, type StoredFacetView } from "./facet-store.js";
export { loadFacetFiles, type FacetFile } from "./facet-store.js";
export {
  LEGION_TEAMS_DIRECTORY,
  loadProfileReferences,
  type ProfileReferences,
  type TeamReference,
  type UnreadableTeamFile,
} from "./references.js";
export {
  ARCHIVE_ENTRY_NAMES,
  bindSessionToProfile,
  createProfile,
  DELETION_LOG_FILE,
  deleteProfile,
  EDITABLE_FACET_KEYS,
  EDITABLE_PROFILE_KEYS,
  inspectProfile,
  loadBindings,
  loadFacetDetail,
  loadFacetSummaries,
  loadProfileBody,
  loadProfileSummaries,
  loadSuspensionHistory,
  reclaimScopeOf,
  restoreProfileBody,
  revisionOf,
  rewriteSoulFile,
  RUNTIME_DIRECTORY_NAME,
  saveFacetMarkdown,
  saveProfileBody,
  saveProfileDisplayFields,
  selectFacetForProfile,
  setFirstMeetingDone,
  setProfileSuspended,
  SOUL_HISTORY_DIRECTORY_NAME,
  SOUL_HISTORY_LOG_FILE,
  SUSPENSION_LOG_FILE,
  TRASH_DIRECTORY_NAME,
  unbindSession,
  type FacetDetail,
  type FacetSummary,
  type ProfileBodyView,
  type ProfileDeletion,
  type ProfileInspection,
  type ProfileSummary,
  type ProfileSuspension,
  type ReclaimScopeEntry,
  type SessionBindingSummary,
  type SoulBodyHistoryEntry,
  type SuspensionEntry,
} from "./soul-library.js";
export { SoulLibrary, type SoulLibraryConfig } from "./soul-service.js";
export {
  createRefusalNotifications,
  REFUSAL_NOTIFICATION_SOURCE_ID,
  REFUSAL_RING_SIZE,
  SoulRefusalLog,
  type RefusalDescriber,
  type SoulRefusalInput,
  type SoulRefusalItem,
  type SoulRefusalList,
  type SoulRefusalSource,
} from "./refusals.js";
export { MAX_TEXT_FILE_BYTES, decodeUtf8Text, readUtf8TextFile } from "./text-file.js";
